FROM {{ item.image }}

ENV container=docker
RUN apt-get update && apt-get install -y --no-install-recommends \
    systemd systemd-sysv \
    python3 python3-pip python3-apt \
    sudo curl gnupg ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /lib/systemd/system/multi-user.target.wants/* \
            /etc/systemd/system/*.wants/* \
            /lib/systemd/system/local-fs.target.wants/* \
            /lib/systemd/system/sockets.target.wants/*udev* \
            /lib/systemd/system/sockets.target.wants/*initctl* \
            /lib/systemd/system/basic.target.wants/* \
            /lib/systemd/system/anaconda.target.wants/*

VOLUME ["/sys/fs/cgroup", "/run", "/run/lock", "/tmp"]
STOPSIGNAL SIGRTMIN+3
CMD ["/lib/systemd/systemd"]
